### ISSUE TITLE
make template repsitory

### ISSUE THREAD

**Issue by rohan999chaudhary** [nschloe/pyfoobar#12]
![image](https://user-images.githubusercontent.com/81921175/122602011-c2adc180-d08f-11eb-9659-600161de7542.png)

**Comment by rohan999chaudhary** [comment]
more  better
![image](https://user-images.githubusercontent.com/81921175/122602124-ebce5200-d08f-11eb-9375-18fe0c6f64ff.png)

**Comment by nschloe** [comment]
Done, thanks for the hint!

**Comment by rohan999chaudhary** [comment]
I think this is a bad idea. As your instructions are for downloading the zip file and renaming.

**Comment by nschloe** [comment]
The instructions can be used one way or the other.
